### ISSUE TITLE
Feature request: Scrap mangas

### ISSUE THREAD

**Issue by AXeL-dev** [AXeL-dev/anime-tracker#17]
### Summary

Scraping mangas websites & listing the latest mangas chapters would be a great addition.

### Motivation

I always forget to check for the newly released mangas chapters, [ato sore wa komaru desu](https://translate.google.com/?hl=fr&sl=ja&tl=en&text=ato%20sore%20wa%20komaru%20desu&op=translate).

### To-Do

- [ ] Add a new/separate section for mangas.
- [ ] Implement `MangasCrawler` class & `Mangas`, `Chapter` types.
- [ ] Offer links to read/download mangas chapters.
- [ ] Implement a favorite mangas service/modify the existing service?
- [ ] Add settings for mangas.
